services:
  db:
    image: postgres:16-alpine
    container_name: wokora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wokora
      POSTGRES_PASSWORD: wokora
      POSTGRES_DB: wokorafoods
    ports:
      - "5432:5432"
    volumes:
      - wokora_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wokora -d wokorafoods"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: wokora-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  wokora_pg:
